const happySongsObj = {
     happySongs: [
          {
               artist: "Pharrell Williams",
               song: "Happy",
               url: "https://www.youtube.com/embed/ZbZSe6N_BXs",
               lyrics: "It might seem crazy what I am 'bout to say<br>Sunshine she's here, you can take a break<br>I'm a hot air balloon that could go to space<br>With the air, like I don't care, baby by the way<br>Huh (Because I'm happy)<br>Clap along if you feel like a room without a roof<br>(Because I'm happy)<br>Clap along if you feel like happiness is the truth<br>(Because I'm happy)<br>Clap along if you know what happiness is to you<br>(Because I'm happy)<br>Clap along if you feel like that's what you wanna do<br>Here come bad news talking this and that (Yeah)<br>Well give me all you got, don't hold back (Yeah)<br>Well I should probably warn you I'll be just fine (Yeah)<br>No offence to you don't waste your time<br>Here's why<br>Clap along if you feel like a room without a roof<br>(Because I'm happy)<br>Clap along if you feel like happiness is the truth<br>(Because I'm happy)<br>Clap along if you know what happiness is to you<br>(Because I'm happy)<br>Clap along if you feel like that's what you wanna do<br>Uh, bring me down<br>Can't nothing, bring me down<br>My level's too high to bring me down<br>Can't nothing, bring me down, I said<br>Bring me down, can't nothing<br>Bring me down<br>My level's too high to bring me down<br>Can't nothing, bring me down, I said<br>Clap along if you feel like a room without a roof<br>(Because I'm happy)<br>Clap along if you feel like happiness is the truth<br>(Because I'm happy)<br>Clap along if you know what happiness is to you<br>(Because I'm happy)<br>Clap along if you feel like that's what you wanna do<br>Clap along if you feel like a room without a roof<br>(Because I'm happy)<br>Clap along if you feel like happiness is the truth<br>(Because I'm happy)<br>Clap along if you know what happiness is to you<br>(Because I'm happy)<br>Clap along if you feel like that's what you wanna do<br>Uh, bring me down (Happy, happy, happy, happy)<br>Can't nothing (Happy, happy, happy, happy)<br>Bring me down, my level's too high<br>To bring me down (Happy, happy, happy, happy)<br>Can't nothing (Happy, happy, happy, happy)<br>Bring me down, I said<br>Clap along if you feel like a room without a roof<br>(Because I'm happy)<br>Clap along if you feel like happiness is the truth<br>(Because I'm happy)<br>Clap along if you know what happiness is to you (ayy, ayy, ayy)<br>(Because I'm happy)<br>Clap along if you feel like that's what you wanna do<br>Clap along if you feel like a room without a roof<br>(Because I'm happy)<br>Clap along if you feel like happiness is the truth<br>(Because I'm happy)<br>Clap along if you know what happiness is to you (hey)<br>(Because I'm happy)<br>Clap along if you feel like that's what you wanna do<br>Come on",
          },
          {
               artist: "Queen",
               song: "Don't Stop Me Now",
               url: "https://www.youtube.com/embed/HgzGwKwLmgM",
               lyrics: "Tonight I'm gonna have myself a real good time<br>I feel alive<br>And the world I'll turn it inside out, yeah<br>I'm floating around in ecstasy<br>So, (don't stop me now)<br>(Don't stop me)<br>'Cause I'm having a good time, having a good time<br>I'm a shooting star leaping through the sky<br>Like a tiger defying the laws of gravity<br>I'm a racing car passing by like Lady Godiva<br>I'm gonna go, go, go<br>There's no stopping me<br>I'm burnin' through the sky, yeah<br>200 degrees<br>That's why they call me Mister Fahrenheit<br>I'm travelling at the speed of light<br>I wanna make a supersonic man out of you<br>I'm having such a good time<br>I'm having a ball<br>(Don't stop me now)<br>If you wanna have a good time just give me a call<br>(Don't stop me now)<br>'Cause I'm having a good time<br>(Don't stop me now)<br>Yes, I'm havin' a good time<br>I don't want to stop at all<br>Yeah, I'm a rocket ship on my way to Mars<br>On a collision course<br>I am a satellite I'm out of control<br>I am a sex machine ready to reload<br>Like an atom bomb about to<br>Oh, oh, oh, oh, oh, explode<br>I'm burnin' through the sky, yeah<br>200 degrees<br>That's why they call me Mister Fahrenheit<br>I'm travelling at the speed of light<br>I wanna make a supersonic woman of you<br>Don't stop me, don't stop me<br>Don't stop me, hey, hey, hey<br>Don't stop me, don't stop me<br>Ooh, ooh, ooh, I like it<br>Don't stop me, don't stop me<br>Have a good time, good time<br>Don't stop me, don't stop me, ah<br>Let loose, honey, all right<br>Oh, I'm burnin' through the sky, yeah<br>200 degrees<br>That's why they call me Mister Fahrenheit<br>I'm travelling at the speed of light<br>I wanna make a supersonic man out of you<br>I'm having such a good time<br>I'm having a ball<br>(Don't stop me now)<br>If you wanna have a good time (alright)<br>Just give me a call<br>(Don't stop me now)<br>'Cause I'm having a good time<br>(Don't stop me now)<br>Yes, I'm havin' a good time<br>I don't want to stop at all<br>La-da-da-da-dah<br>Da-da-da-ha<br>Ha-da-da, ha-ha-ha<br>Ha-da-da, ha-da-da-ah",
          },
          {
               artist: "Lizzo",
               song: "About Damn Time",
               url: "https://www.youtube.com/embed/tRQe3HjZEzw",
               lyrics: "It's bad bitch o'clock, yeah, it's thick-thirty<br>I've been through a lot but I'm still flirty (okay)<br>Is everybody back up in the buildin'?<br>It's been a minute, tell me how you're healin'<br>'Cause I'm about to get into my feelings<br>How you feelin'? How you feel right now?<br>Oh, I've been so down and under pressure<br>I'm way too fine to be this stressed, yeah<br>Oh, I'm not the girl I was or used to be<br>Uh, bitch, I might be better<br>Turn up the music, turn down the lights<br>I got a feelin' I'm gon' be alright<br>Okay (okay), alright<br>It's about damn time (time)<br>Turn up the music, let's celebrate (alright)<br>I got a feelin' I'm gon' be okay<br>Okay (okay), alright<br>It's about damn time<br>In a minute I'ma need a sentimental<br>Man or woman to pump me up<br>Feeling fussy, walkin' in my Balenci-ussy's<br>Tryna bring out the fabulous<br>'Cause I give a fuck way too much<br>I'ma need like two shots in my cup<br>Wanna get up, wanna get down<br>Mm, that's how I feel right now<br>Oh, I've been so down and under pressure<br>I'm way too fine to be this stressed, yeah<br>Oh, I'm not the girl I was or used to be<br>Uh, bitch, I might be better<br>Turn up the music, turn down the lights<br>I got a feelin' I'm gon' be alright<br>Okay (okay), alright<br>It's about damn time (time)<br>Turn up the music, let's celebrate (alright)<br>I got a feelin' I'm gon' be okay<br>Okay (okay), alright<br>It's about damn time<br>Bitch<br>'Cause, uh, you know that time it is, uh<br>I'm comin' out tonight, I'm comin' out tonight (uh-huh)<br>I'm comin' out tonight, I'm comin' out tonight (woo)<br>I'm comin' out tonight, I'm comin' out tonight<br>Okay (okay), alright (alright)<br>It's about damn time<br>I'm comin' out tonight, (let's go) I'm comin' out tonight (comin' out tonight)<br>I'm comin' out tonight, I'm comin' out tonight (woo)<br>I'm comin' out tonight, I'm comin' out tonight (comin' out tonight)<br>Okay (okay), alright<br>It's about damn time<br>Oh<br>Bitch<br>Yeah, yeah<br>It's about damn time",
          },
          {
               artist: "Prince",
               song: "Let's Go Crazy",
               url: "https://www.youtube.com/embed/dmwLlj51iTA",
               lyrics: "Dearly beloved<br>We are gathered here today<br>To get through this thing called &quot;life&quot;<br>Electric word, life<br>It means forever and that's a mighty long time<br>But I'm here to tell you there's something else<br>The afterworld<br>A world of never ending happiness<br>You can always see the sun, day or night<br>Let's go crazy (woo)<br>Let's go crazy<br>Let's go crazy<br>Let's go crazy<br>If you don't like<br>The world you're living in<br>Take a look around<br>At least you got friends<br>You see I called my old lady<br>For a friendly word<br>She picked up the phone<br>Dropped it on the floor<br>Ah, ah is all I heard<br>Are we gonna let de-elevator bring us down?<br>Oh no, lets go<br>Let's go crazy<br>Let's get nuts<br>Let's look for the purple banana<br>Until they put us in the truck, let's go<br>Oh yeah yeah yeah<br>Yeah yeah yeah, there it is<br>Yeah yeah, no no (oh yeah)<br>We're all excited (all excited)<br>Don't know why (I don't know why)<br>Maybe it's 'cause<br>We're all gonna die<br>When we do<br>What's it all for? (What's it all for?)<br>Better live now<br>Before the grim reaper comes knocking on your door<br>Tell me, are we gonna let elevator bring us down?<br>Oh no, let's go<br>Let's go crazy (let's go crazy)<br>Let's get nuts (let's get nuts)<br>Let's look for the purple banana<br>Until they put us in the truck, let's go<br>C'mon, baby<br>Let's get nuts<br>Yeah<br>Oh (Crazy)<br>Are we gonna let elevator bring us down?<br>Oh no, let's go<br>Let's go crazy (let's go crazy)<br>Let's get nuts (let's get nuts)<br>Let's look for the purple banana (let's look)<br>Until they put us in the truck, let's go ('til they put us in the truck)<br>Let's go<br>Dr. Everything'll be alright<br>Make everything go wrong<br>Oh<br>Ooh<br>Yeah yeah, let's go",
          },
          {
               artist: "Hall & Oates",
               song: "You Make My Dreams",
               url: "https://www.youtube.com/embed/EErSKhC0CZs",
               lyrics: "What I want you've got<br>And it might be hard to handle<br>Like the flame that burns the candle<br>The candle feeds the flame, yeah, yeah<br>What I've got's full stock<br>Of thoughts and dreams that scatter<br>Then you pull them all together<br>And how I can't explain<br>Oh, yeah<br>Well, well you<br>(Ooh-ho, hoo-ooh, ooh-oo)<br>You make my dreams come true<br>(You-hoo, you, you-hoo, hoo, you, hoo)<br>Well, well, well you<br>(You-hoo, hoo-hoo-ooh)<br>Oh, yeah<br>You make my dreams come true<br>(You make my dreams)<br>Come true<br>(You-hoo, you, you-hoo, hoo, you, hoo)<br><br>On a night when bad dreams become a screamer<br>When they're messin' with the dreamer<br>I can laugh it in the face<br>Twist and shout my way out<br>And wrap yourself around me<br>'Cos I ain't the way you found me<br>And I'll never be the same<br>Oh, yeah<br>Well, 'cos you<br>(Ooh-ho, hoo-ooh, ooh-oo)<br>You make my dreams come true<br>(You-hoo, you, you-hoo, hoo, you, hoo)<br>Well, well, well you<br>(You-hoo, hoo-hoo-ooh)<br>You make my dreams come true<br>(You make my dreams)<br>Come true<br>(You-hoo, you, you-hoo, hoo, you, hoo)<br><br>Listen to this<br><br>I'm down on my daydream<br>Oh, that sleepwalk should be over by now<br>I know<br>'Bout you<br>Yeah, yeah<br>You make my dreams come true<br>(You-hoo, you, you-hoo, hoo, you, hoo)<br>Oh, yeah<br>I've waited, waited for you, girl<br>(You-hoo, hoo-hoo-ooh)<br>Oh, yeah<br>You make my dreams come true<br>(You make my dreams)<br>Come true<br>(You-hoo, you, you-hoo, hoo, you, hoo)<br>You and me, you and me...",
          },
          {
               artist: "Taylor Swift",
               song: "Shake It Off",
               url: "https://www.youtube.com/embed/nfWlot6h_JM",
               lyrics: "I stay out too late, got nothing in my brain<br>That's what people say, that's what people say<br>I go on too many dates, but I can't make them stay<br>At least that's what people say, that's what people say<br>But I keep cruising<br>Can't stop, won't stop moving<br>It's like I got this music in my mind<br>Saying it's gonna be alright<br>I never miss a beat, I'm lightning on my feet<br>And that's what they don't see, that's what they don't see<br>Players gonna play, play, play, play, play<br>And the haters gonna hate, hate, hate, hate, hate (haters gonna hate)<br>Baby, I'm just gonna shake, shake, shake, shake, shake<br>I shake it off, I shake it off<br>Heartbreakers gonna break<br>Fakers gonna fake<br>I'm just gonna shake<br>I shake it off, I shake it off<br>I shake it off, I shake it off<br>I, I, I shake it off, I shake it off<br>I, I, I shake it off, shake it off<br>I, I, I shake it off, I shake it off<br>I, I, I shake it off, I shake it off<br>I, I, I shake it off, I shake it off<br>I, I, I, shake it off, I shake it off<br>I, I, I, shake it off, I shake it off",
          },
          {
               artist: "BTS",
               song: "Dynamite",
               url: "https://www.youtube.com/embed/OiMWFojB9Ok",
               lyrics: "'Cause I-I-I'm in the stars tonight<br>So watch me bring the fire and set the night alight<br>Shoes on, get up in the morn'<br>Cup of milk, let's rock and roll<br>King Kong, kick the drum, rolling on like a Rolling Stone<br>Sing song when I'm walking home<br>Jump up to the top, LeBron<br>Ding dong, call me on my phone<br>Ice tea and a game of ping pong, huh<br>This is getting heavy<br>Can you hear the bass boom? I'm ready (woo hoo)<br>Life is sweet as honey<br>Yeah, this beat cha-ching like money, huh<br>Disco overload, I'm into that, I'm good to go<br>I'm diamond, you know I glow up<br>Hey, so let's go<br>'Cause I-I-I'm in the stars tonight<br>So watch me bring the fire and set the night alight (hey)<br>Shining through the city with a little funk and soul<br>So I'ma light it up like dynamite, whoa oh oh<br>Bring a friend, join the crowd<br>Whoever wanna come along<br>Word up, talk the talk<br>Just move like we off the wall<br>Day or night, the sky's alight<br>So we dance to the break of dawn<br>Ladies and gentlemen, I got the medicine<br>So you should keep ya eyes on the ball, huh<br>This is getting heavy<br>Can you hear the bass boom? I'm ready (woo hoo)<br>Life is sweet as honey<br>Yeah, this beat cha-ching like money<br>Disco overload, I'm into that, I'm good to go<br>I'm diamond, you know I glow up<br>Let's go<br>'Cause I-I-I'm in the stars tonight<br>So watch me bring the fire and set the night alight (hey)<br>Shining through the city with a little funk and soul<br>So I'ma light it up like dynamite, whoa oh oh<br>Dy-na-na-na, na-na, na-na-na, na-na-na, life is dynamite<br>Dy-na-na-na, na-na, na-na-na, na-na-na, life is dynamite<br>Shining through the city with a little funk and soul<br>So I'ma light it up like dynamite, whoa oh oh<br>Dy-na-na-na, na-na, na-na, ayy<br>Dy-na-na-na, na-na, na-na, ayy<br>Dy-na-na-na, na-na, na-na, ayy<br>Light it up like dynamite<br>Dy-na-na-na, na-na, na-na, ayy<br>Dy-na-na-na, na-na, na-na, ayy<br>Dy-na-na-na, na-na, na-na, ayy<br>Light it up like dynamite<br>'Cause I-I-I'm in the stars tonight<br>So watch me bring the fire and set the night alight<br>Shining through the city with a little funk and soul<br>So I'ma light it up like dynamite (this is ah)<br>'Cause I-I-I'm in the stars tonight<br>So watch me bring the fire and set the night alight (alight, oh)<br>Shining through the city with a little funk and soul<br>So I'ma light it up like dynamite, whoa (light it up like dynamite)<br>Dy-na-na-na, na-na, na-na-na, na-na-na, life is dynamite<br>Dy-na-na-na, na-na, na-na-na, na-na-na, life is dynamite<br>Shining through the city with a little funk and soul<br>So I'ma light it up like dynamite, whoa oh oh",
          },
          {
               artist: "Bruno Mars",
               song: "24K Magic",
               url: "https://www.youtube.com/embed/UqyT8IEBkvY",
               lyrics: "Tonight<br>I just want to take you higher<br>Throw your hands up in the sky<br>Let's set this party off right<br>Players, put yo' pinky rings up to the moon<br>Girls, what y'all trying to do?<br>Twenty four karat magic in the air<br>Head to toe so player<br>Look out uh<br>Pop pop, it's show time (show time)<br>Show time (show time)<br>Guess who's back again?<br>Oh they don't know? (Go on tell 'em)<br>Oh they don't know? (Go on tell 'em)<br>I bet they know soon as we walk in (showin' up)<br>Wearing Cuban links (ya)<br>Designer minks (ya)<br>Inglewood's finest shoes (whoop, whoop)<br>Don't look too hard might hurt ya'self<br>Known to give the color red the blues<br>Oh shit, I'm a dangerous man with some money in my pocket (keep up)<br>So many pretty girls around me and they waking up the rocket (keep up)<br>Why you mad, fix ya face, ain't my fault y'all be jocking (keep up)<br>Players only, come on<br>Put your pinky rings up to the moon<br>Girls, what y'all trying to do?<br>Twenty four karat magic in the air<br>Head to toe so player<br>Uh, look out!<br>Second verse for the hustlas (hustlas) gangstas (gangstas)<br>Bad bitches and ya ugly ass friends (haha)<br>Can I preach? (uh oh) can I preach? (uh oh)<br>I gotta show 'em how a pimp get it in<br>First, take your sip (sip), do your dip (dip)<br>Spend your money like money ain't shit (whoop, whoop)<br>We too fresh<br>Got to blame in on Jesus<br>Hashtag blessed, they ain't ready for me<br>I'm a dangerous man with some money in my pocket (keep up)<br>So many pretty girls around me and they waking up the rocket (keep up)<br>Why you mad, fix ya face, ain't my fault y'all be jocking (keep up)<br>Players only, come on<br>Put your pinky rings up to the moon<br>Hey girls<br>What y'all trying to do? (What y'all trying to do?)<br>Twenty four karat magic in the air<br>Head to toe so player<br>Uh, look out!<br>everywhere I go they be like<br>Ooh, so player<br>Everywhere I go they be like (ooh, so player ooh)<br>Oh everywhere I go they be like (ooh, so player ooh)<br>Now, now, now watch me break it down like (uh)<br>Twenty four karat, twenty four karat magic<br>What's that sound (twenty four karat, twenty four karat magic)<br>Come on now<br>Twenty four karat, twenty four karat magic<br>Don't fight the feeling, invite the feeling<br>Just put your pinky rings up to the moon<br>Girls, what y'all trying to do? (Tell me what y'all trying to do)<br>Twenty four karat magic in the air<br>Head to toe so player (hands up!)<br>Put your pinky rings up to the moon<br>Girls, what y'all trying to do? (Do)<br>Twenty four karat magic in the air<br>Head to toe so player (twenty four karat) uh, look out",
          },
          {
               artist: "Stevie Wonder",
               song: "Sir Duke",
               url: "https://www.youtube.com/embed/s6fPN5aQVDI",
               lyrics: `Music is a world within itself\nWith a language we all understand\nWith an equal opportunity\nFor all to sing, dance and clap their hands\nBut just because a record has a groove\nDon't make it in the groove\nBut you can tell right away at letter A\nWhen the people start to move\n\nThey can feel it all over\nThey can feel it all over people\nThey can feel it all over\nThey can feel it all over people\n\nMusic knows it is and always will\nBe one of the things that life just won't quit\n\nBut here are some of music's pioneers\nThat time will not allow us to forget\nFor there's Basie, Miller, Satchmo\nAnd the king of all Sir Duke\nAnd with a voice like Ella's ringing out\nThere's no way the band can lose\n\nYou can feel it all over\nYou can feel it all over people\nYou can feel it all over\nYou can feel it all over people\n\nYou can feel it all over\nYou can feel it all over people\nYou can feel it all over\nYou can feel it all over people\n\nYou can feel it all over\n\nYou can feel it all over people\nYou can feel it all over\nYou can feel it all over people\n\nYou can feel it all over\nYou can feel it all over people\nYou can feel it all over\nI can feel it all over-all over now people\n\nCan't you feel it all over\nCome on let's feel it all over people\nYou can feel it all over\nEverybody-all over people`,
          },
          {
               artist: "Electric Light Orchestra",
               song: "Mr. Blue Sky",
               url: "https://www.youtube.com/embed/wuJIqmha2Hk",
               lyrics: "Sun is shinin' in the sky<br>There ain't a cloud in sight<br>It's stopped rainin' everybody's in the play<br>And don't you know<br>It's a beautiful new day, hey hey<br>Runnin' down the avenue<br>See how the sun shines brightly in the city<br>On the streets where once was pity<br>Mr. Blue Sky is living here today, hey hey<br>Mr. Blue Sky please tell us why<br>You had to hide away for so long (so long)<br>Where did we go wrong?<br>Mr. Blue Sky please tell us why<br>You had to hide away for so long (so long)<br>Where did we go wrong?<br>Hey you with the pretty face<br>Welcome to the human race<br>A celebration, Mr. Blue Sky's up there waitin'<br>And today is the day we've waited for<br>Oh Mr. Blue Sky please tell us why<br>You had to hide away for so long (so long)<br>Where did we go wrong?<br>Hey there Mr. Blue<br>We're so pleased to be with you<br>Look around see what you do<br>Everybody smiles at you<br>Hey there Mr. Blue<br>We're so pleased to be with you<br>Look around see what you do<br>Everybody smiles at you<br>Mr. Blue, you did it right<br>But soon comes Mr. Night creepin' over<br>Now his hand is on your shoulder<br>Never mind I'll remember you this<br>I'll remember you this way<br>Mr. Blue Sky please tell us why<br>You had to hide away for so long (so long)<br>Where did we go wrong?<br>Hey there Mr. Blue (sky)<br>We're so pleased to be with you (sky)<br>Look around see what you do (blue)<br>Everybody smiles at you",
          },
     ],
};

module.exports = { happySongsObj };
