const loveSongsObj = {
     loveSongs: [
          {
               artist: "NAO",
               song: "Adore You",
               url: "https://www.youtube.com/embed/oCgQK2SUM3M",
               lyrics: `You're giving me fever<br> You're making the pressure rise at night right through my veins<br> You're making my heart sing<br> You're making my voice reach places that it's never been no, no, no, no<br> You're making me weak, yeah<br> My mind's awake all night daydreaming when will you be mine?<br> You're making my sleep wait<br> Thinking of you is taking all my nights away-way-way<br> I really do adore you<br> Oh, lovely<br> I really do adore you, you, you, you<br> Oh, lovely<br> Oh, I really do adore<br> And I adore you too<br> I've been thinking that your love's kinda special<br> You should know that I love and adore you too<br> Missing you at night<br> You're my addiction, so compulsive, it's my right<br> I'm drowning in your smile<br> You're so contagious, spreading through me got my fever up all night<br> And I can feel you through the night and moving through me I can't fight it<br> You're my obsession, intoxicated<br> And you know that you do this to me<br> Cast your spell so you can rule me<br> Surrender to you<br> My lovely<br> I really do adore you<br> My lovely<br> I really do adore you, you, you, you<br> Oh, my lovely, yeah<br> I really do adore you, you, you, you<br> I really adore you, hey<br> You're my night time, you're my daytime<br> Sun, moon, and rain, do-do-do<br> I really adore you, oh<br> I really do adore<br> And I adore you too<br> I've been thinking that your love's kinda special<br> You should know that I love and adore you too<br> You<br> Adore you<br> Adore you<br> Adore you<br> Adore you<br> Adore you<br> Adore you<br> Adore you`,
          },
          {
               artist: "Mac Miller",
               song: "We",
               url: "https://www.youtube.com/embed/XL--KSNxfy8",
               lyrics: `Yeah, well you could be my<br> Said you could be my<br> Yeah, you could be my<br> Yeah, okay, well you could be my<br> Baby you could be my<br> Baby you could be my<br> Well okay, it's alright, it's okay<br> Okay, well you could be my<br> Well okay, it's alright, it's okay<br> You could be my<br> Yeah, well okay, it's alright, it's okay<br> Said you could be my<br> Well okay, it's alright, it's okay<br> Said you could be my<br> Well, you ain't in the mood to argue<br> Baby don't you worry, this some shit to get along to<br> Some shit I right my wrongs to<br> Well, I've tried to call you, have us a discussion<br> We never talk, we always way too busy fuckin'<br> I'll think of something to say, I always do<br> I'm in love with the way that you say my name<br> Every time it sound brand new<br> And you, always wonderin' what we'll be<br> I say we sound better than you or me<br> Baby you could be my (Woo!)<br> Well okay, it's alright, it's okay<br> Yeah, I feel like you could be my<br> Well okay, it's alright, it's okay<br> And I can be your<br> Well okay, it's alright, it's okay<br> Only if you be my<br> It's alright, it's okay<br> Yeah, okay, and time will tell<br> If I'm alive and well, 'cause when I'm by myself<br> I find that I keep flying high, sometimes I must remind myself<br> That change is more than pennies laying on the floor inside a well<br> You cross my mind, do not apologize for being fine as hell<br> I'm spinning here inside your spell, my mind has start to wander<br> I missed a day, I stay up late admiring your posture<br> And you, always wonderin' what we'll be<br> I say we sound better than you or me<br> Baby you could be my<br> Yeah, well okay, it's alright, it's okay<br> And baby you could be my<br> Well okay, it's alright, it's okay<br> And I can be your<br> Well okay, it's alright, it's okay<br> Yeah, only if you be my<br> There's no more you or me, me or we, sweetheart<br> (Just be your sweet babe)<br> And I can see, I can see, so much better<br> I can see<br> I'm carefully, precious things fall apart<br> Just let them be, let it be, forever<br> Oh, loving me, in spite of me<br> Bless your heart, bless your heart<br> I can breathe, I can breathe so much better, yeah<br> I won't let anything tear us apart, no, no, no<br> We are we, we are we, forever<br> You could be my<br> Well okay, it's alright<br> I said you could be my<br> Well okay, it's alright, it's okay<br> And I can be your<br> Well okay, it's alright, it's okay<br> Only if you be my<br> It's alright, it's okay<br> You gotta deal with Mac Miller, bitch`,
          },
          {
               song: "Into The Red",
               artist: "James Blake",
               url: "https://www.youtube.com/embed/hujTeTsD-nk",
               lyrics: `The list of things I could live without<br> Grows longer as I move everything around<br> Behind all the furniture<br> Pointed towards her<br> To keep her in my sights<br> To keep her in my life<br> By all means, she can get ahead of herself<br> I'll already be there<br> I'll already be there to meet her<br> She's no traitor<br> I've got no chaser<br> For a leg up<br> I've got no chaser<br> She's no traitor<br> For a joint account<br> She gave me everything that she had left<br> Anything for herself<br> But for me she goes way in, way in<br> Way into the red<br> She saw every hand in my pocket<br> She saw the gold rush<br> She watched me lose face everyday<br> Rather than lose me<br> She was the gold rush<br> She was the gold rush<br> She was the gold rush<br> She saw every hand in her pocket<br> And she sawed off every hand<br> Anything for herself<br> But for me she goes way in, way in<br> Way into the red<br> She saw every hand in my pocket<br> She saw the gold rush<br> She watched me lose face everyday<br> Rather than lose me<br> She was the gold rush<br> She was the gold rush<br> She was the gold rush<br> She was the gold rush<br> She was the gold rush<br> She was the gold rush<br> What I have will believe you until now<br> Even doing nothing, I am making the most of somehow<br> And the credit goes to her<br> It's the bad day speaking red<br> Gotta keep her in my sights<br> Gotta keep her in my life<br> By all means, she can get ahead of herself<br> I'll already be there<br> I'll already be there to meet her`,
          },
          {
               artist: "Boyz II Men",
               song: "That's Why I Love You",
               url: "https://www.youtube.com/embed/9QpyEUtJNaA",
               lyrics: `Uh yeah<br> Say it once<br> Uh, mmm<br> Yeah<br> When it's dawning (when it's dawning)<br> You're my sunshine<br> When my mind gets clouded (gets clouded)<br> You've been the light inside<br> When it's hard for me to breathe<br> You're the air I need<br> Sometimes I make you want to leave<br> But you're always there for me<br> That's why I love (I)<br> That's why I love (said I love you baby baby)<br> I love (don't you know I love)<br> That's why I love you (and you know and you know)<br> That's why I love (don't you know you're so right baby)<br> A girl I love (Mmmm)<br> I want to everyone to know (said I want the world to know)<br> That I love you (hey ey)<br> Date think it for now<br> When I'm crying<br> You're my handkerchief<br> It feels like I'm dying<br> You raise me up just once again<br> Baby you're the star<br> When I'm lost<br> The guy asks my way<br> At time when I'm losing my mind<br> You make everything OK<br> That's why I, I love you<br> I love you<br> That's why I love (I love you so)<br> Oh, yes I do<br> I love<br> I really do<br> That's why I love<br> I love you, I love you, I love you eh<br> That's why I love<br> And girl I love you<br> That's why I love<br> I want everyone to know<br> That I love you<br> I love you, I love you, I love you<br> I love it when you come around<br> Cause you know just how to hold me down<br> Said you show enough time to hypnotize<br> You're so beautiful and ain't no doubt<br> I knew baby what would I do<br> I lose hold to my breath to explain to you<br> That I love you<br> That is why I<br> That's why I love (I love you baby)<br> That's why I love<br> I love<br> That's why I love you<br> That's why I love ah ah ah<br> And girl love you<br> I want everyone to know<br> That I love you<br> I love you, I love you, I love you<br> That's why I love<br> That's why I love<br> I love (I love you so much)<br> That's why I love you (Oh oh oh yes)<br> That's why I love<br> And girl I love (Huh)<br> I want everyone to know<br> That I love you (Oh I love you)<br> That's why I love<br> That's why I love (Hey)<br> I love<br> That's why I love you<br> That's why I love ah ah ah<br> And girl I love<br> I want everyone to know<br> That I love you<br> I love (I love you)<br> I love<br> Ha ha ha<br> That's why I love<br> And girl I love<br> I want everyone to know<br> That I love you<br> Hey`,
          },
          {
               artist: "Frank Ocean",
               song: "Thinkin Bout You",
               url: "https://www.youtube.com/embed/6JHu3b-pbh8",
               lyrics: `A tornado flew around my room before you came\nExcuse the mess it made, it usually doesn't rain in\nSouthern California, much like Arizona\nMy eyes don't shed tears, but boy, they bawl\n\nWhen I'm thinkin' bout ya, ooh no no no\n\nI've been thinkin' bout ya, you know know know\n\nI've been thinkin' bout ya, do you think about me still?\n\nDo ya? Do ya?\n\n\n\nOr do you not think so far ahead?\n\n'Cause I've been thinkin' bout forever, ooh\n\nOr do you not think so far ahead?\n\n'Cause I've been thinkin' bout forever, ooh\n\n\n\nNo, I don't like you, i just thought you were cool enough to kick it\n\nGot a beach house I could sell you in Idaho\n\nSince you think I don't love you, I just thought you were cute, that's why I kiss you\n\nGot a fighter jet I don't get to fly it though I'm lying down\n\n\n\nThinkin' bout ya, ooh no no no\n\nI've been thinkin' bout ya, you know know know\n\nI've been thinkin' bout ya, do you think about me still?\n\nDo ya? Do ya?\n\n\n\nOr do you not think so far ahead?\n\n'Cause I've been thinkin' bout forever, ooh\n\nOr do you not think so far ahead?\n\n'Cause I've been thinkin' bout forever, ooh\n\n\n\nYes, of course I remember, how could I forget how you feel?\n\nYou know you were my first time, a new feel\n\nIt will never get old, not in my soul, not in my spirit, keep it alive\n\nWe'll go down this road 'til it turns from color to black and white\n\n\n\nOr do you not think so far ahead?\n\n'Cause I've been thinkin' bout forever, ooh\n\nOr do you not think so far ahead?\n\n'Cause I've been thinkin' bout forever, ooh`,
          },
          {
               artist: "Miguel",
               song: "Sure Thing",
               url: "https://www.youtube.com/embed/q4GJVOMjCC4",
               lyrics: `Love you like a brother<br> Treat you like a friend<br> Respect you like a lover<br> Oh, oh, oh, oh, oh, oh<br> You could bet that<br> Never gotta sweat that<br> You could bet that<br> Never gotta sweat that<br> You could bet that<br> Never gotta sweat that<br> You could bet that<br> Never gotta sweat that<br> If you be the cash<br> I'll be the rubber band<br> You be the match<br> I will be a fuse, boom<br> Painter baby, you could be the muse<br> I'm the reporter baby, you could be the news<br> 'Cause you're the cigarette and I'm the smoker<br> We raise a bet, cause you're the joker<br> Checked off, you are a chalk<br> And I can be the blackboard<br> You could be the talk<br> And I could be the walk<br> Even when the sky comes falling<br> Even when the sun don't shine<br> I got faith in you and I<br> So put your pretty little hand in mine<br> Even when we're down to the wire baby<br> Even when it's do or die<br> We could do it baby, simple and plain<br> 'Cause this love is a sure thing<br> You could bet that<br> Never gotta sweat that<br> You could bet that<br> Never gotta sweat that<br> You could bet that<br> Never gotta sweat that<br> You could bet that<br> Never gotta sweat that<br> Be the lover, I'll be the fighter baby<br> If I'm the blunt, you could be the lighter babe<br> Fire it up<br> Writer baby, you could be the quote<br> If I'm the lyric baby, you could be the note, record that<br> Saint I'm a sinner, prize I'm a winner and it's you<br> What did I do to deserve that<br> Paper baby, I'll be the pen<br> Say that I'm the one, cause you are a ten<br> Even when the sky comes falling<br> Even when the sun don't shine<br> I got faith in you and I<br> So put your pretty little hand in mine<br> Even when we're down to the wire baby<br> Even when it's do or die<br> We could do it baby, simple and plain<br> 'Cause this love is a sure thing<br> This love between you and I is simple as pie baby<br> It's such a sure thing (such a sure thing)<br> Ooh it such a sure thing (such a sure thing)<br> Even when the sky comes falling<br> Even when the sun don't shine<br> I got faith in you and I<br> So put your pretty little hand in mine<br> Even when we're down to the wire baby<br> Even when it's do or die<br> We could do it baby, simple and plain<br> 'Cause this love is a sure thing<br> Love you like a brother<br> Treat you like a friend<br> Respect you like a lover<br> Oh, oh, oh, oh, oh, oh`,
          },
          {
               artist: "Vance Joy",
               song: "Riptide",
               url: "https://www.youtube.com/embed/uJ_1HMAGb4k",
               lyrics: `I was scared of dentists and the dark<br> I was scared of pretty girls and starting conversations<br> Oh, all my friends are turning green<br> You're the magician's assistant in their dream<br> Ah-ooh-ooh-ooh, ah-ahh-ah-ah<br> And they come unstuck<br> Lady, running down to the riptide<br> Taken away to the dark side<br> I wanna be your left hand man<br> I love you when you're singing that song<br> And I got a lump in my throat<br> 'Cause you're gonna sing the words wrong<br> There's this movie that I think you'll like<br> This guy decides to quit his job and heads to New York City<br> This cowboy's running from himself<br> And she's been living on the highest shelf<br> Ah-ooh-ooh-ooh, ah-ahh-oh<br> And they come unstuck<br> Lady, running down to the riptide<br> Taken away to the dark side<br> I wanna be your left hand man<br> I love you when you're singing that song<br> And I got a lump in my throat<br> 'Cause you're gonna sing the words wrong<br> I just wanna, I just wanna know<br> If you're gonna, if you're gonna stay<br> I just gotta, I just gotta know<br> I can't have it, I can't have it any other way<br> I swear she's destined for the screen<br> Closest thing to Michelle Pfeiffer that you've ever seen, oh<br> Lady, running down to the riptide<br> Taken away to the dark side<br> I wanna be your left hand man<br> I love you when you're singing that song<br> And I got a lump in my throat<br> 'Cause you're gonna sing the words wrong<br> Oh lady, running down to the riptide<br> Taken away to the dark side<br> I wanna be your left hand man<br> I love you when you're singing that song<br> And I got a lump in my throat<br> 'Cause you're gonna sing the words wrong<br> Oh lady, running down to the riptide<br> Taken away to the dark side<br> I wanna be your left hand man<br> I love you when you're singing that song<br> And I got a lump in my throat<br> 'Cause you're gonna sing the words wrong<br> Yeah, I got a lump in my throat<br> 'Cause you're gonna sing the words wrong`,
          },
          {
               artist: "Imagine Dragons",
               song: "Next To Me",
               url: "https://www.youtube.com/embed/Txlk7PiHaGk",
               lyrics: `Something about the way that you walked into my living room<br> Casually and confident lookin' at the mess I am<br> But still you, still you want me<br> Stress lines and cigarettes, politics and deficits<br> Late bills and overages, screamin' and hollerin'<br> But still you, still you want me<br> <br> Oh, I always let you down<br> You're shattered on the ground<br> But still I find you there<br> Next to me<br> And oh, stupid things I do<br> I'm far from good, it's true<br> But still I find you<br> Next to me<br> <br> There's something about the way that you always see the pretty view<br> Overlook the mud and mess, always lookin' effortless<br> And still you, still you want me<br> I got no innocence, faith ain't no privilege<br> I am a deck of cards, vice or a game of hearts<br> And still you, still you want me<br> <br> Oh, I always let you down<br> You're shattered on the ground<br> But still I find you there<br> Next to me<br> And oh, stupid things I do<br> I'm far from good, it's true<br> But still I find you<br> Next to me<br> <br> So thank you for taking a chance on me<br> I know it isn't easy<br> But I hope to be worth it<br> So thank you for taking a chance on me<br> I know it isn't easy<br> But I hope to be worth it<br> <br> Oh, I always let you down (I always let you down)<br> You're shattered on the ground (shattered on the ground)<br> But still I find you there<br> Next to me<br> And oh, stupid things I do (stupid things I do)<br> I'm far from good, it's true<br> But still I find you<br> Next to me (next to me)`,
          },
          {
               artist: "Alicia Keys",
               song: "Show Me Love",
               url: "https://www.youtube.com/embed/vNf1tfEtfXI",
               lyrics: `Show me love<br> Treat it like we freakin' on the weekend, show me love<br> I heat up the seconds, times and reasons for your love<br> This is not the season for nobody else but us<br> I always get wrapped up in you, baby, I'm in love<br> We gon' get this love, yeah, like we never done it<br> Baby, I'm in love<br> Go 'head, show me love, like we never done it<br> Ooh, I got you runnin' every time I give you some<br> Show me love, love<br> Show me love, love<br> Show me love like, you see red lights<br> And you crashed in it like a deer inside of headlights<br> Yeah, I showed you love like it was passionate<br> I just wanna bask in it, winnin' it like a championship<br> You gon' show me love like, like you tried it (yeah) and denied it (yeah)<br> But you still let me apply it (yeah) like I made you put your ties in<br> Show me lo-o-ove, even when you don't got time to<br> I'll be there to find ya, I'll remind ya<br> Show me love<br> Treat it like we freakin' on the weekend, show me love<br> I heat up the seconds, times and reasons for your love<br> This is not the season for nobody else but us<br> I always get wrapped up in you, baby, I'm in love<br> We gon' get this love, yeah, like we never done it<br> Baby, I'm in love<br> Go 'head, show me love, like we never done it<br> Ooh, I got you runnin' every time I give you some<br> Show me love, love, love, love, love<br> Show me love, love, love, love, love<br> Baby, you know what it is, yeah<br> You know what it is, yeah<br> You know what it is, yeah (yeah, yeah, yeah-yeah-yeah)<br> You know what it is, yeah (yeah-yeah-yeah, yeah-yeah-yeah)<br> You gon' show what it means to love (yeah)<br> What it is<br> You gon' show what it means to love (yeah)<br> What it is<br> Show me love<br> Treat it like we freakin' on the weekend, show me love<br> I heat up the seconds, times and minutes for your love<br> This is not the season for nobody else but us<br> I always get wrapped up, baby, baby, I'm in love<br> We gon' get this love, yeah (we gon' get it, get it)<br> Like we never done it (we never did it)<br> Baby, I'm in love<br> Go 'head, show me love, like we never done it<br> Yeah, I got you runnin' every time I give you some<br> Yeah`,
          },
          {
               artist: "Mariah Carey",
               song: "Always Be My Baby",
               url: "https://www.youtube.com/embed/LfRNRymrv9k",
               lyrics: `Do do doop dum<br> Do do doop do doop da dum<br> Do do doop dum<br> Do do doop do doop da dum<br> Do do doop do do do<br> Do do doop do doop da dum<br> Do do doop dum<br> Do do doop do doop da dum<br> We were as one, babe<br> For a moment in time<br> And it seemed everlasting<br> That you would always be mine<br> Now you want to be free<br> So I'm lettin' you fly<br> 'Cause I know in my heart babe<br> Our love will never die<br> No you'll always be a part of me<br> I'm part of you indefinitely<br> Boy don't you know you can't escape me<br> Oh darlin' 'cause you'll always be my baby<br> And we'll linger on<br> Time can't erase a feelin' this strong<br> No way you're never gonna shake me<br> Oh darlin' cause you'll always be my baby<br> Do do doop<br> Do do doop do doop da dum<br> Do do doop dum<br> Do do doop do doop da dum<br> I ain't gonna cry, no<br> And I won't beg you to stay<br> If you're determined to leave boy<br> I will not stand in your way<br> But inevitably you'll be back again<br> 'Cause you know in your heart, babe<br> Our love will never end, no<br> You'll always be apart of me<br> I'm part of you indefinitely<br> Boy don't you know you can't escape me<br> Oh darlin' 'cause you'll always be my baby<br> And we'll linger on<br> Time can't erase a feelin' this strong<br> No way you're never gonna shake me<br> Oh darlin' 'cause you'll always be my baby<br> I know that you'll be back boy<br> When your days and your nights get a little bit colder oh<br> (I know that)<br> You'll be right back, baby<br> Oh baby believe me it's only a matter of time, time<br> You'll always be apart of me<br> I'm part of you indefinitely<br> Boy don't you know you can't escape me<br> Oh darlin' 'cause you'll always be my baby<br> And we'll linger on<br> Time can't erase a feelin' this strong<br> No way you're never gonna shake me<br> Ooh darlin' 'cause you'll always be my baby<br> You'll always be a part of me<br> I'm part of you indefinitely<br> Boy don't you know you can't escape me, yeah<br> Oh darlin' 'cause you'll always be my baby<br> And we'll linger on<br> (You and I will always be)<br> Time can't erase a feelin' this strong<br> (You and I)<br> No way you're never gonna shake me<br> (You and I)<br> Ooh darlin' 'cause you'll always be my baby<br> (You and I)<br> Do do doop<br> (You and I will always be)<br> Do do doop do doop da dum<br> (No way you're never gonna change me)<br> Do do doop dum<br> (No way you're never gonna stray me)<br> Do do doop do doop da dum<br> Do do doop<br> (You and I will always be)`,
          },
     ],
};

module.exports = { loveSongsObj };
