const sadSongsObj = {
     sadSongs: [
          {
               artist: "Amy Winehouse",
               song: "Back to Black",
               url: "https://www.youtube.com/embed/4Q4Gy2Z7xZ0",
               lyrics: `He left no time to regret\n Kept his dick wet\n With his same old safe bet\n Me and my head high\n And my tears dry\n Get on without my guy\n You went back to what you knew\n So far removed\n From all that we went through\n And I tread a troubled track\n My odds are stacked\n I'll go back to black\n We only said goodbye with words\n I died a hundred times\n You go back to her\n And I go back to\n I go back to us\n I love you much\n It's not enough\n You love blow and I love puff\n And life is like a pipe\n And I'm a tiny penny\n Rolling up the walls inside\n We only said goodbye with words\n I died a hundred times\n You go back to her\n And I go back to\n We only said goodbye with words\n I died a hundred times\n You go back to her\n And I go back to\n Black, black\n Black, black\n Black, black\n Black\n I go back to\n I go back to\n We only said goodbye with words\n I died a hundred times\n You go back to her\n And I go back to\n We only said goodbye with words\n I died a hundred times\n You go back to her\n And I go back to black\n`,
          },
          {
               artist: "Lorde",
               song: "Liability",
               url: "https://www.youtube.com/embed/BtvJaNeELic",
               lyrics: `Baby really hurt me, crying in the taxi\n He don't wanna know me\n Says he made the big mistake of dancing in my storm\n Says it was poison\n So I guess I'll go home\n Into the arms of the girl that I love\n The only love I haven't screwed up\n She's so hard to please, but she's a forest fire\n I do my best to meet her demands, play at romance, we slow dance\n In the living room, but all that a stranger would see\n Is one girl swaying alone, stroking her cheek\n They say, &quot;You're a little much for me\n You're a liability\n You're a little much for me&quot;\n So they pull back, make other plans\n I understand, I'm a liability\n Get you wild, make you leave\n I'm a little much for e-a-na-na-na, everyone\n The truth is I am a toy that people enjoy\n 'Til all of the tricks don't work anymore\n And then they are bored of me\n I know that it's exciting running through the night, but\n Every perfect summer's eating me alive until you're gone\n Better on my own\n They say, &quot;You're a little much for me\n You're a liability\n You're a little much for me&quot;\n So they pull back, make other plans\n I understand, I'm a liability\n Get you wild, make you leave\n I'm a little much for e-a-na-na-na, everyone\n They're gonna watch me disappear into the sun\n You're all gonna watch me disappear into the sun`,
          },
          {
               artist: "The Weeknd",
               song: "Call Out My Name",
               url: "https://www.youtube.com/embed/rsEne1ZiQrk",
               lyrics: `We found each other\n I helped you out of a broken place\n You gave me comfort\n But falling for you was my mistake\n I put you on top, I put you on top\n I claimed you so proud and openly\n And when times were rough, when times were rough\n I made sure I held you close to me\n So call out my name (call out my name)\n Call out my name when I kiss you so gently\n I want you to stay (I want you to stay)\n I want you to stay, even though you don't want me\n Girl, why can't you wait? (why can't you wait, baby?)\n Girl, why can't you wait 'til I fall out of love?\n Won't you call out my name? (call out my name)\n Girl, call out my name, and I'll be on my way and\n I'll be on my\n I said I didn't feel nothing baby, but I lied\n I almost cut a piece of myself for your life\n Guess I was just another pit stop\n 'Til you made up your mind\n You just wasted my time\n You're on top, I put you on top\n I claimed you so proud and openly, babe\n And when times were rough, when times were rough\n I made sure I held you close to me\n So call out my name (call out my name, baby)\n So call out my name when I kiss you\n So gently, I want you to stay (I want you to stay)\n I want you to stay even though you don't want me\n Girl, why can't you wait? (girl, why can't you wait 'til I)\n Girl, why can't you wait 'til I fall out of loving?\n Babe, call out my name (say call out my name, baby)\n Girl, call out my name, and I'll be on my way, girl\n I'll be on my\n On my way, all the way\n On my way, all the way, ooh\n On my way, on my way, on my way\n On my way, on my way, on my way\n (On my)`,
          },
          {
               artist: "Billie Eilish",
               song: "bitches broken hearts",
               url: "https://www.youtube.com/embed/qpQSjf-0Lc8",
               lyrics: `You can pretend you don't miss me (me)\n You can pretend you don't care\n All you wanna do is kiss me (me) \n Oh, what a shame I'm not there\n You can pretend you don't miss me (me)\n You can pretend you don't care\n All you wanna do is kiss me (me)\n Oh, what a shame I'm not there\n What is it you want?\n You can lie but I know that you're not fine\n Every time you talk\n It's all 'bout me, but you swear I'm not on your mind\n You can pretend you don't miss me (me)\n You can pretend you don't care \n All you wanna do is kiss me (me)\n Oh, what a shame I'm not there\n Everybody knows\n You and I are suicide and stolen art\n Pretty mama sews\n Stitches into all your bitches' broken hearts\n You can pretend you don't miss me (me)\n You can pretend you don't care\n All you wanna do is kiss me (me)\n Oh, what a shame I'm not there\n Somebody new is gonna comfort you\n Like you want me to\n Somebody new is gonna comfort me\n Like you never do\n Every now and then, it hits me\n That I'm the one that got away\n But I guess bein' lonely fits me\n And you were made for begging, &quot;Stay&quot;`,
          },
          {
               artist: "Drake",
               song: "Feel No Ways",
               url: "https://www.youtube.com/embed/jnpQTXs1PZ0",
               lyrics: `I should be downtown, whippin' on the way to you\n You got somethin' that belongs to me\n Your body language says it all\n Despite the things you said to me\n Who is it that's got you all gassed up? (yeah)\n Changin' your opinion on me\n I was only gone for the last few months\n But you don't have the time to wait on me (yeah)\n I tried with you\n There's more to life than sleepin' in and gettin' high with you\n I had to let go of us to show myself what I could do\n And that just didn't sit right with you (yeah)\n And now you're tryna make me feel a way, on purpose\n Now you're throwin' it back in my face, on purpose\n Now you're talkin' down on my name, on purpose (yeah)\n And you don't feel no way, you think I deserve it\n Feel a way, feel a way, young nigga feel a way\n I've stopped listenin' to things you say\n 'Cause you don't mean it anyway (yeah)\n Feel a way, feel a way, young nigga feel a way\n Maybe we just should have did things my way\n Instead of the other way\n I tried with you\n There's more to life than sleepin' in and gettin' high with you\n I had to let go of us to show myself what I could do\n And that just didn't sit right with you (yeah)\n And now you're tryna make me feel a way, on purpose\n Now you're throwin' it back in my face, on purpose\n Now you're talkin' down on my name, on purpose (yeah)\n And you don't feel no way, you think I deserve it\n`,
          },
          {
               artist: "Snoh Alegra",
               song: "LOST YOU",
               url: "https://www.youtube.com/embed/YKeXXnyvMgI",
               lyrics: `Didn't know that love could change up\n Then I woke up to a stranger\n After all this time I thought that I knew\n You and I was no debating\n Now it's up for conversation\n Tell me was it all a lie? I'm confused (mmm)\n But then you say what I wanna hear\n 'Cause you know it's gon' get me here\n Every time I say that I'm through\n And even though I know it ain't right\n Said I wasn't gon' spend the night\n Here I am right back with you\n Although I lost you\n I, I'll always want you\n 'Cause you take me high (high)\n See I'll always want you\n But I know I've lost you (ah)\n Say it, right\n Ah, ah-ah-ah\n I won't hold the past against you\n When you hold me, I forget to\n I can never draw the line with you, no\n Wish I knew what you were thinking\n But that probably wouldn't change shit\n So deep in, I'm still falling for you\n But then you say what I wanna hear\n 'Cause you know it's gon' get me here\n Every time I say that I'm through\n And even though I know it ain't right\n Said I wasn't gon' spend the night\n Here I am right back with you\n Although I lost you\n I, I'll always want you (I'll always want you)\n 'Cause you take me high (high)\n See I'll always want you\n But I know I've lost you\n Ah-da-da-da-da (yeah)\n Ah-ah-ah`,
          },
          {
               artist: "Conan Gray",
               song: "Yours",
               url: "https://www.youtube.com/embed/74NhLkjIeMs",
               lyrics: `I'm somebody you call when you're alone\n I'm somebody you use, but never own\n I'm somebody you touch, but never hold\n And you're somebody I'll never really know\n I know I'm not the one you really love\n I guess that's why I've never given up\n 'Cause I could give you all you want, the stars and the sun\n But still, I'm not enough\n Oh-oh, all I really wanted was that look in your eyes\n Like you already know that I'm the love of your life\n Like you already know you're never sayin' goodbye\n But I'm not yours\n I'm not yours, I'm not yours\n I want more, I want more\n But I'm not yours\n And I can't change your mind\n But you're still mine\n So tell me that it's time for me to go\n 'Cause you know I can't do it on my own\n The only thing that's harder than sleepin' alone\n Is sleepin' with your ghost\n Oh-oh, all I really wanted was that look in your eyes\n Like you already know that I'm the love of your life\n Like you already know you're never sayin' goodbye\n But I'm not yours\n I'm not yours, I'm not yours\n I want more, I want more\n But I'm not yours\n And I can't change your mind\n I should've known that it was dumb love\n 15 dozen roses\n All the things that I've done for you not to notice\n Can't believe I chose you over all my best friends\n What the fuck did I do in the end?\n Just to not be yours`,
          },
          {
               artist: "Johnny Orlando",
               song: "someone will love you better",
               url: "https://www.youtube.com/embed/1skpo8ziUsA",
               lyrics: `The greatest romance, lightning strike to my heart\n We would slow dance, in the headlights, in the parking lot\n There was no chance of ever falling apart\n But you've noticed that I'm here, but I'm so far\n 'Cause I've been running from the sun\n And I've got nowhere left to hide (oh)\n Every night I close my eyes\n And wish I was still in love\n Trying to fight, at war with my mind\n It's gonna kill me to give you up\n Darling, this is gonna hurt\n No, I won't regret it\n 'Cause I loved you first\n But someone will love you better\n Last time I hold you\n Just 'cause you needed heart to console you\n When I can't give you reasons\n Hate that love can be a thing you lose\n There's nothing you or I could do\n We were fools to fall and it's nobody's fault, no\n 'Cause I've been running from the sun\n And I've got nowhere left to hide\n Every night I close my eyes\n And wish I was still in love\n Trying to fight, at war with my mind\n It's gonna kill me to give you up\n Darling, this is gonna hurt\n No, I won't regret it\n 'Cause I loved you first\n But someone will love you better\n Ooh-ooh-ooh\n Ooh-ooh-ah\n 'Cause I loved you first (I loved you first)\n But someone will love you better\n Ooh-ooh-ooh\n Ooh-ooh-ah\n 'Cause I loved you first\n But someone will love you better\n Darling, this is gonna hurt\n I won't regret it\n 'Cause I loved you first\n But someone will love you better\n`,
          },
          {
               artist: "Bill Withers",
               song: "Ain't No Sunshine",
               url: "https://www.youtube.com/embed/CICIOJqEb5c",
               lyrics: `Ain't no sunshine when she's gone\n It's not warm when she's away\n Ain't no sunshine when she's gone\n And she's always gone too long\n Anytime she's goes away\n Wonder this time where she's gone\n Wonder if she's gone to stay\n Ain't no sunshine when she's gone\n And this house just ain't no home\n Anytime she goes away\n And I know, I know, I know, I know\n I know, I know, I know, I know, I know\n I know, I know, I know, I know, I know\n I know, I know, I know, I know, I know\n I know, I know, I know, I know, I know\n I know, I know\n Hey I oughta leave young thing alone\n But ain't no sunshine when she's gone, woh woh\n Ain't no sunshine when she's gone\n Only darkness every day\n Ain't no sunshine when she's gone\n And this house just ain't no home\n Anytime she goes away\n Anytime she goes away\n Anytime she goes away\n Anytime she goes away`,
          },
          {
               artist: "Labrinth",
               song: "Jealous",
               url: "https://www.youtube.com/embed/50VWOBi0VFs",
               lyrics: `I'm jealous of the rain\n That falls upon your skin\n It's closer than my hands have been\n I'm jealous of the rain\n I'm jealous of the wind\n That ripples through your clothes\n It's closer than your shadow\n Oh, I'm jealous of the wind, cause\n I wished you the best of\n All this world could give\n And I told you when you left me\n There's nothing to forgive\n But I always thought you'd come back, tell me all you found was\n Heartbreak and misery\n It's hard for me to say, I'm jealous of the way\n You're happy without me\n I'm jealous of the nights\n That I don't spend with you\n I'm wondering who you lay next to\n Oh, I'm jealous of the nights\n I'm jealous of the love\n Love that was in here\n Gone for someone else to share\n Oh, I'm jealous of the love, cause\n I wished you the best of\n All this world could give\n And I told you when you left me\n There's nothing to forgive\n But I always thought you'd come back, tell me all you found was\n Heartbreak and misery\n It's hard for me to say, I'm jealous of the way\n You're happy without me\n As I sink in the sand\n Watch you slip through my hands\n Oh, as I die here another day\n Cause all I do is cry behind this smile\n I wished you the best of\n All this world could give\n And I told you when you left me\n There's nothing to forgive\n But I always thought you'd come back, tell me all you found was\n Heartbreak and misery\n It's hard for me to say, I'm jealous of the way\n You're happy without me\n It's hard for me to say, I'm jealous of the way\n You're happy without me\n `,
          },
     ],
};

module.exports = { sadSongsObj };
