import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import clientPromise from '../lib/mongodb'
import TodoItem from './todoItem'
import InputField from './inputField.tsx'


export default function Home({todos}) {
  const todoList = JSON.parse(todos)
  return (
    <div className={styles.container}>
      <Head>
        <title>Todo List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={'mb-10 text-6xl'}>
          Tasker
        </h1>
        <InputField />
        <div className={styles.grid}>
        {todoList.map((todo) => (
          <TodoItem title={todo.title} text={todo.text} completed={todo.completed} />
        ))}
        </div>
      </main>

    </div>
  )
}
export async function getServerSideProps(context) {
  try {
    const client = await clientPromise
    const db = client.db('todo')
    let todos = await db.collection('todos').find({}).toArray()
    todos = JSON.stringify(todos)

    return {
      props: { todos: todos,
              isConnected: true },
    }
  } catch (e) {
    console.error(e)
    return {
      props: { isConnected: false },
    }
  }
}