export const data = [
  {
    name: 'Edamame',
    description: 'Immature soybeans boiled and topped with salt',
    category: 'otsumami',
    img: 'edamame.webp',
    stock: 0,
    id: '43tr4y5',
  },
  {
    name: 'Sesame Spinach',
    description: 'Blanched spinach with salt and sesame oil',
    category: 'otsumami',
    img: 'spinach.webp',
    stock: 6,
    id: '8097s3s',
  },
  {
    name: 'Onigiri',
    description: 'Small rice ball mixed with furikake',
    category: 'otsumami',
    img: 'onigiri.jpg',
    stock: 5,
    id: '652ljfy',
  },
  {
    name: 'Iced Kyuuri',
    description: 'Cold cucumber with miso paste',
    category: 'otsumami',
    img: 'cucumber.webp',
    stock: 5,
    id: '10n24sj',
  },
  {
    name: 'Negima',
    description: 'Chicken thigh and green onions with tare sauce',
    category: 'skewers',
    img: 'negima.jpg',
    stock: 10,
    id: '936sbvt',
  },
  {
    name: 'Tsukune',
    description: 'Chicken meatballs covered in tare sauce',
    category: 'skewers',
    img: 'tsukune.webp',
    stock: 4,
    id: '025sl4q',
  },
  {
    name: 'Kirin',
    description: 'Kirin Ichiban Japanese Lager',
    category: 'drinks',
    img: 'kirin.jpg',
    stock: 5,
    id: 'kjsy91p',
  },
  {
    name: 'Umeshu Soda',
    description: 'Aged Umeshu mixed with soda water',
    category: 'drinks',
    img: 'umeshu-soda.jpg',
    stock: 0,
    id: 'cno2a8',
  },
];
